'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.33440
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




'INSTANT C# NOTE: Formerly VB project-level imports:
Imports AllForms
Imports Microsoft.VisualBasic.ApplicationServices

Namespace Project
    Namespace My

        'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
        ' or if you encounter build errors in this file, go to the Project Designer
        ' (go to Project Properties or double-click the My Project node in
        ' Solution Explorer), and make changes on the Application tab.
        '
        Partial Friend Class MyApplication
            Inherits WindowsFormsApplicationBase

            <DebuggerStepThrough()> _
            Public Sub New()
                MyBase.New(AuthenticationMode.Windows)
                Me.IsSingleInstance = False
                Me.EnableVisualStyles = True
                Me.SaveMySettingsOnExit = True
                Me.ShutdownStyle = ShutdownMode.AfterMainFormCloses
            End Sub

            <DebuggerStepThrough()> _
            Protected Overrides Sub OnCreateMainForm()
                Me.MainForm = Login.DefaultInstance
            End Sub

            Private Shared MyApp As MyApplication
            Friend Shared ReadOnly Property Application() As MyApplication
                Get
                    Return MyApp
                End Get
            End Property

            <STAThread()> _
            Shared Sub Main(ByVal args() As String)
                System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(False)
                MyApp = New MyApplication()
                MyApp.Run(args)
            End Sub

        End Class
    End Namespace

End Namespace