//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbInstaller.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n        DROP DATABASE if exists CDTH;\r\n\r\n        CREATE DATABASE CDTH;\r\n\r\n     " +
            "   use cdth;\r\n\r\n        DROP TABLE IF EXISTS `customer`;\r\n        CREATE TABLE `" +
            "customer` (\r\n        `Cus_Id` int(11) NOT NULL,\r\n        `Cus_Name` varchar(255)" +
            " DEFAULT NULL,\r\n        `Cus_Address` varchar(255) DEFAULT NULL,\r\n        `Cus_G" +
            "ov` varchar(255) DEFAULT NULL,\r\n        `Cus_Tel` varchar(255) DEFAULT NULL,\r\n  " +
            "      `Cus_Email` varchar(255) DEFAULT NULL,\r\n        PRIMARY KEY (`Cus_Id`)\r\n  " +
            "      ) ENGINE=InnoDB DEFAULT CHARSET=utf8;\r\n\r\n\r\n        INSERT INTO `customer` " +
            "VALUES (\'4\', \'ปรีดา วิชัย\', \'อ.หงาว จ.ระนอง\', \'วิทยาลัยเทคนิคระนอง\', \'08-1232323" +
            "2\', \'fofun@gmail.com\');\r\n        INSERT INTO `customer` VALUES (\'6\', \'แววดาว แสง" +
            "พราว\', \'อ.สุขสำราญ จ.ระนอง\', \'อบต.สุขสำราญ\', \'08-15438799\', \'style@hotmail.com\')" +
            ";\r\n        INSERT INTO `customer` VALUES (\'8\', \'ปกรณ์ สุขใจ\', \'8/1 ม.5 ต.บางริ้น" +
            " อ.เมือง จ.ระนอง\', \'เทศบาลเมืองระนอง\', \'08-78896541\', \'pakon@hotmail.com\');\r\n   " +
            "     INSERT INTO `customer` VALUES (\'9\', \'กติกา ดวงดี\', \'ระนอง\', \'บางริ้น\', \'08-" +
            "67315808\', \'rung@gail.com\');\r\n        INSERT INTO `customer` VALUES (\'10\', \'สหาย" +
            " จงรัก\', \'ระนอง\', \'บางริ้น\', \'08-86310999\', \'jongruk@hotmail.com\');\r\n        INS" +
            "ERT INTO `customer` VALUES (\'11\', \'หรรษา มากาย\', \'ระนอง\', \'เทศบาลระนอง\', \'08-874" +
            "62099\', \'hunsa@gmail.com\');\r\n\r\n\r\n        DROP TABLE IF EXISTS `employee`;\r\n     " +
            "   CREATE TABLE `employee` (\r\n        `Emp_Id` int(11) NOT NULL,\r\n        `Emp_N" +
            "ame` varchar(255) DEFAULT NULL,\r\n        `Emp_Address` varchar(255) DEFAULT NULL" +
            ",\r\n        `Emp_Tel` varchar(255) DEFAULT NULL,\r\n        `Emp_Position` varchar(" +
            "255) DEFAULT NULL,\r\n        `Emp_Salary` double DEFAULT NULL,\r\n        PRIMARY K" +
            "EY (`Emp_Id`)\r\n        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;\r\n\r\n        INSERT I" +
            "NTO `employee` VALUES (\'8\', \'สุฑิตา แซ่อุ่ย\', \' 8/10 ม.1 ต.บางริ้น อ.เมือง จ.ระน" +
            "อง\', \'08-48423957\', \'พนักงานออกแบบ\', \'11000\');\r\n        INSERT INTO `employee` V" +
            "ALUES (\'9\', \'ณัฐนรี บุญญารัตน์\', \'อ.เมือง จ.ระนอง\', \'08-66734523\', \'พนักงานออกแบ" +
            "บ\', \'11000\');\r\n        INSERT INTO `employee` VALUES (\'10\', \'กังสชิต กรเกษม\', \'7" +
            "77 ม.1 ต.บางริ้น อ.เมือง จ.ระนอง\', \'08-58889999\', \'ช่างเครื่อง\', \'8900\');\r\n     " +
            "   INSERT INTO `employee` VALUES (\'11\', \'พงศธร โชติมณีโรจน์\', \'พ่อตาขิง ระนอง\', " +
            "\'08-00034335\', \'เจ้าของกิจการ\', \'15000\');\r\n        INSERT INTO `employee` VALUES" +
            " (\'12\', \'ธนาคาร\', \'โรงพยาบาล\', \'08-12469211\', \'ช่างเครื่องช่างเครื่อง\', \'10000\')" +
            ";\r\n        INSERT INTO `employee` VALUES (\'15\', \'ณเดช คุกกี้มั้ยจ๊ะ\', \'ระนอง\', \'" +
            "08-61340997\', \'ผู้ดูแลระบบ\', \'9000\');\r\n        INSERT INTO `employee` VALUES (\'1" +
            "6\', \'สมหมาย จงดี\', \'ระนอง\', \'08-54210056\', \'ผู้ดูแลบัญชี\', \'9000\');\r\n\r\n        D" +
            "ROP TABLE IF EXISTS `orders`;\r\n        CREATE TABLE `orders` (\r\n        `Job_Id`" +
            " int(11) NOT NULL,\r\n        `Job_Name` varchar(255) DEFAULT NULL,\r\n        `Job_" +
            "Class` varchar(255) DEFAULT NULL,\r\n        `Job_Num` int(11) DEFAULT NULL,\r\n    " +
            "    `Job_Size` varchar(255) DEFAULT NULL,\r\n        `Job_Price` decimal(19,4) DEF" +
            "AULT NULL,\r\n        `Job_Date` datetime DEFAULT NULL,\r\n        `Job_Sent` dateti" +
            "me DEFAULT NULL,\r\n        `Job_Script` varchar(255) DEFAULT NULL,\r\n        `Cus_" +
            "Id` int(11) DEFAULT NULL,\r\n        `Emp_Id` int(11) DEFAULT NULL,\r\n        `Job_" +
            "Status` varchar(255) DEFAULT NULL,\r\n        PRIMARY KEY (`Job_Id`)\r\n        ) EN" +
            "GINE=InnoDB DEFAULT CHARSET=utf8;\r\n\r\n\r\n        INSERT INTO `orders` VALUES (\'1\'," +
            " \'ป้ายน้ำมันเครื่อง Fast Fast\', \'ไวนิล\', \'11\', \'0.50x0.50\', \'550.0000\', \'2015-04" +
            "-16 00:00:00\', \'2015-03-16 00:00:00\', \'\', \'4\', \'10\', \'ชำระแล้ว\');\r\n        INSER" +
            "T INTO `orders` VALUES (\'2\', \'สติ๊กเกอร์ PVC\', \'สติ๊กเกอร์ PVC\', \'1\', \'1x1\', \'55" +
            "0.0000\', \'2015-04-16 00:00:00\', \'2015-03-16 00:00:00\', \'\', \'6\', \'10\', \'ชำระแล้ว\'" +
            ");\r\n        INSERT INTO `orders` VALUES (\'3\', \'ป้ายไวนิล น้ำมันตราแมว\', \'ไวนิล\'," +
            " \'1\', \'1x1\', \'200.0000\', \'2015-04-16 00:00:00\', \'2015-03-16 00:00:00\', \'\', \'4\', " +
            "\'10\', \'ค้างชำระ\');\r\n        INSERT INTO `orders` VALUES (\'4\', \'1111\', \'สติ๊กเกอร" +
            "์ PVC\', \'1\', \'1x1\', \'550.0000\', \'2015-03-20 00:00:00\', \'2015-03-19 00:00:00\', \'\'" +
            ", \'4\', \'10\', \'ชำระแล้ว\');\r\n        INSERT INTO `orders` VALUES (\'5\', \'เรียบร้อย " +
            "ใสๆ\', \'สติ๊กเกอร์ PVC\', \'1\', \'1x1\', \'550.0000\', \'2015-03-20 00:00:00\', \'2015-03-" +
            "20 00:00:00\', \'\', \'4\', \'10\', \'ค้างชำระ\');\r\n        INSERT INTO `orders` VALUES (" +
            "\'6\', \'รูปดอกกล้วยไม้\', \'สติ๊กเกอร์ซีทรู\', \'1\', \'1x1\', \'800.0000\', \'2015-04-16 00" +
            ":00:00\', \'2015-03-16 00:00:00\', \'\', \'8\', \'10\', \'ชำระแล้ว\');\r\n        INSERT INTO" +
            " `orders` VALUES (\'7\', \'ป้ายบอกทาง\', \'ไวนิล\', \'1\', \'0.50x0.50\', \'50.0000\', \'2015" +
            "-03-30 00:00:00\', \'2015-03-31 00:00:00\', \'สี่เหลี่ยม ลูกศรทางซ้าย พื้นขาว ตัวแดง" +
            "\', \'8\', \'10\', \'ค้างชำระ\');\r\n        INSERT INTO `orders` VALUES (\'8\', \'ป้ายจราจร" +
            "\', \'ไวนิล\', \'1\', \'1x1\', \'200.0000\', \'2015-03-30 00:00:00\', \'2015-03-31 00:00:00\'" +
            ", \'ลูกศรด้านขวา พื้นขาว ตัวแดง\', \'8\', \'10\', \'ค้างชำระ\');\r\n        INSERT INTO `o" +
            "rders` VALUES (\'9\', \'เทศบาลเมืองระนอง\', \'สติ๊กเกอร์ไดคัท\', \'2\', \'2x3\', \'6600.000" +
            "0\', \'2015-04-16 00:00:00\', \'2015-03-16 00:00:00\', \'\', \'9\', \'10\', \'ชำระแล้ว\');\r\n " +
            "       INSERT INTO `orders` VALUES (\'10\', \'ป้ายดอกกุหลาบ\', \'ไวนิล\', \'1\', \'1x1\', " +
            "\'200.0000\', \'2015-04-16 00:00:00\', \'2015-03-16 00:00:00\', \'\', \'10\', \'16\', \'ค้างช" +
            "ำระ\');\r\n        INSERT INTO `orders` VALUES (\'11\', \'ตุ๊กตาบาบี้\', \'สติ๊กเกอร์ซีท" +
            "รู\', \'2\', \'2x2\', \'6400.0000\', \'2015-04-16 00:00:00\', \'2015-03-16 00:00:00\', \'\', " +
            "\'11\', \'16\', \'ชำระแล้ว\');\r\n        INSERT INTO `orders` VALUES (\'12\', \'กราฟฟิค\', " +
            "\'สติ๊กเกอร์ฝ้า\', \'2\', \'3x2\', \'6600.0000\', \'2015-04-16 00:00:00\', \'2015-03-16 00:" +
            "00:00\', \'\', \'11\', \'16\', \'ชำระแล้ว\');\r\n        INSERT INTO `orders` VALUES (\'13\'," +
            " \'11111\', \'สติ๊กเกอร์ฝ้า\', \'1\', \'2x2\', \'1100.0000\', \'2015-04-16 00:00:00\', \'2015" +
            "-03-16 00:00:00\', \'\', \'11\', \'10\', \'มัดจำ 50% \');\r\n\r\n\r\n        DROP TABLE IF EXIS" +
            "TS `usertable`;\r\n        CREATE TABLE `usertable` (\r\n        `User_Id` int(11) N" +
            "OT NULL,\r\n        `UserName` varchar(255) NOT NULL,\r\n        `Password` varchar(" +
            "255) DEFAULT NULL,\r\n        `UserLevel` varchar(255) DEFAULT NULL,\r\n        `Emp" +
            "_Id` int(11) DEFAULT NULL,\r\n        PRIMARY KEY (`User_Id`,`UserName`)\r\n        " +
            ") ENGINE=InnoDB DEFAULT CHARSET=utf8;\r\n\r\n\r\n        INSERT INTO `usertable` VALUE" +
            "S (\'1\', \'admin\', \'1234\', \'ผู้ดูแลระบบ\', \'11\');\r\n        INSERT INTO `usertable` " +
            "VALUES (\'2\', \'employee\', \'1234\', \'พนักงาน\', \'10\');\r\n        INSERT INTO `usertab" +
            "le` VALUES (\'3\', \'owner\', \'1234\', \'เจ้าของกิจการ\', \'9\');\r\n        INSERT INTO `u" +
            "sertable` VALUES (\'4\', \'sommy\', \'1234\', \'พนักงาน\', \'16\');\r\n      ")]
        public string sql {
            get {
                return ((string)(this["sql"]));
            }
        }
    }
}
